---
title: "Video06-ExploratoryDataAnalysis"
author: "Max Moro"
date: "September 29, 2018"
output: html_document
---

https://rpubs.com/tmcfl/simulated-click-analysis


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
```

```{r }
datafile='dataNY.rds'
if(!file.exists(datafile)){
  #download files (faster)
  files = paste0("http://stat.columbia.edu/~rachel/datasets/nyt",1:31,".csv")
  if (F)  lapply(files,function(x){download.file(x,destfile=basename(x))})
  
  #read files
  df=data.frame()
  for (i in 1:31){
    message('day:',i)
    dft=read.csv(paste0("nyt",i,".csv"))
    dft$day=i
    df=rbind(df,dft)
  }
  saveRDS(df,datafile)
}
df=readRDS(datafile)

df$ageGroup  <- cut(df$Age, c(-Inf, 18, 24, 34, 44, 54, 64, Inf)
                    ,labels=c('<18','18-24','25-34','35-44','45-54','55-64','65+'))

table(df$ageGroup)

df$Gender = factor(df$Gender,levels=c(1,0),labels=c('male','female'))

table(df$ageGroup,df$Signed_In)
library(ggplot)
ggplot(data=na.omit(df),aes(x=ageGroup,y=Impresions,fill=ageGroup))


```

